# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nix-aarch64-linux = {
    pname = "nix-aarch64-linux";
    version = "2.20.1";
    src = dockerTools.pullImage {
      imageName = "docker.io/nixos/nix";
      imageDigest = "sha256:ab7306ccfa8168ad63f4e91a6217a73decdd641c49c7274212a93df19ee88938";
      sha256 = "sha256-7ymRm6Ts/OW6BZkHl9KOU2lwXzveI4mMXjP72/0QxC0=";
      finalImageTag = "2.20.1";
      arch = "arm64";
    };
  };
  nix-x86_64-linux = {
    pname = "nix-x86_64-linux";
    version = "2.20.1";
    src = dockerTools.pullImage {
      imageName = "docker.io/nixos/nix";
      imageDigest = "sha256:ab7306ccfa8168ad63f4e91a6217a73decdd641c49c7274212a93df19ee88938";
      sha256 = "sha256-QC0NtbztqYuXKRCD8m6vGA0pbL/dKcZulPD+KPGAWD4=";
      finalImageTag = "2.20.1";
      arch = "amd64";
    };
  };
}
