defmodule SowerClient.Schemas.Orchestration.UpgradeRequest do
  use SowerClient.Schema

  OpenApiSpex.schema(%{
    title: "SubscriptionUpgradeRequest",
    type: :object,
    properties: %{
      request_id: %Schema{
        type: :string,
        description: "request sid, autogenerated",
        readOnly: true,
        default: "req_#{Cuid2Ex.create()}"
      },
      subscription_sids: %Schema{
        type: :array,
        items: %Schema{
          type: :string,
          description: "subscription sid allocated by Sower",
          readOnly: true
        }
      }
    },
    required: ~w(subscription_sids)a
  })
end
