defmodule SowerClient.Schemas.Orchestration.UpgradeRequest do
  use SowerClient.Schema

  OpenApiSpex.schema(%{
    title: "SubscriptionUpgradeRequest",
    type: :object,
    properties: %{
      request_id: %Schema{
        type: :string,
        description: "request sid, autogenerated",
        readOnly: true
      },
      subscription_sids: %Schema{
        type: :array,
        items: %Schema{
          type: :string,
          description: "subscription sid allocated by Sower",
          readOnly: true
        }
      }
    },
    required: ~w(subscription_sids)a
  })

  @doc """
  Wrapper around cast() for generating ids
  """
  def new(map) do
    map
    |> Map.put_new_lazy(:request_id, fn -> SowerClient.Schemas.Sid.generate("req") end)
    |> cast()
  end
end
