on:
  push:

env:
  NIKS3_URL: ${{ vars.NIKS3_URL }}
  SOWER_ENDPOINT: ${{ vars.SOWER_ENDPOINT }}

jobs:
  sower:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: go cli
        run: |
          export HOME=$PWD

          nix develop .#ci --command sower build --cache niks3:// --eval-jobs 12 .#sowerJobs.x86_64-linux --push
        env:
          NIKS3_AUTH_TOKEN: ${{ secrets.NIKS3_AUTH_TOKEN }}

  elixir-format:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command just check-elixir-format

  # elixir-test:
  #   runs-on: local/x86_64-linux
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - run: |
  #         export HOME=$PWD
  #         nix develop .# --command just check-elixir-test

  go:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command just check-go

  e2e:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command just check-e2e
