on:
  push:

env:
  ATTIC_URL: ${{ vars.ATTIC_URL }}
  ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
  ATTIC_KEY: ${{ secrets.ATTIC_KEY }}
  SOWER_ENDPOINT: ${{ vars.SOWER_ENDPOINT }}

jobs:
  sower:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: go cli
        run: |
          export HOME=$PWD

          nix develop .#ci --command attic login main $ATTIC_URL --set-default $ATTIC_KEY

          nix develop .#ci --command sower builder push --workers 4 --system x86_64-linux --target "attic:main:$ATTIC_CACHE" --debug
