on:
  push:

jobs:
  build-and-seed-x86_64:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command just check-go
