on:
  push:

jobs:
  go:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command just check-go

  e2e:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix build .#checks.x86_64-linux.default
