on:
  push:

jobs:
  checks:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: go
        run: |
          export HOME=$PWD
          nix develop .# --command just check-go

      - name: e2e
        run: |
          export HOME=$PWD
          nix build .#checks.x86_64-linux.default
