// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.3.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Seed A seed is an installable unit
type Seed struct {
	// Id Name of the seed
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Name of the seed
	Name string `json:"name"`

	// SeedType Type of the seed
	SeedType string `json:"seed_type"`

	// StorePath Store path of the seed
	StorePath string `json:"store_path"`
}

// SowerWebSeedControllerNewJSONRequestBody defines body for SowerWebSeedControllerNew for application/json ContentType.
type SowerWebSeedControllerNewJSONRequestBody = Seed

// SowerWebSeedControllerFindLatestJSONRequestBody defines body for SowerWebSeedControllerFindLatest for application/json ContentType.
type SowerWebSeedControllerFindLatestJSONRequestBody = Seed

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SowerWebSeedControllerList request
	SowerWebSeedControllerList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SowerWebSeedControllerNewWithBody request with any body
	SowerWebSeedControllerNewWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SowerWebSeedControllerNew(ctx context.Context, body SowerWebSeedControllerNewJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SowerWebSeedControllerFindLatestWithBody request with any body
	SowerWebSeedControllerFindLatestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SowerWebSeedControllerFindLatest(ctx context.Context, body SowerWebSeedControllerFindLatestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SowerWebSeedControllerList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSowerWebSeedControllerListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SowerWebSeedControllerNewWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSowerWebSeedControllerNewRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SowerWebSeedControllerNew(ctx context.Context, body SowerWebSeedControllerNewJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSowerWebSeedControllerNewRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SowerWebSeedControllerFindLatestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSowerWebSeedControllerFindLatestRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SowerWebSeedControllerFindLatest(ctx context.Context, body SowerWebSeedControllerFindLatestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSowerWebSeedControllerFindLatestRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSowerWebSeedControllerListRequest generates requests for SowerWebSeedControllerList
func NewSowerWebSeedControllerListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/seeds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSowerWebSeedControllerNewRequest calls the generic SowerWebSeedControllerNew builder with application/json body
func NewSowerWebSeedControllerNewRequest(server string, body SowerWebSeedControllerNewJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSowerWebSeedControllerNewRequestWithBody(server, "application/json", bodyReader)
}

// NewSowerWebSeedControllerNewRequestWithBody generates requests for SowerWebSeedControllerNew with any type of body
func NewSowerWebSeedControllerNewRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/seeds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSowerWebSeedControllerFindLatestRequest calls the generic SowerWebSeedControllerFindLatest builder with application/json body
func NewSowerWebSeedControllerFindLatestRequest(server string, body SowerWebSeedControllerFindLatestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSowerWebSeedControllerFindLatestRequestWithBody(server, "application/json", bodyReader)
}

// NewSowerWebSeedControllerFindLatestRequestWithBody generates requests for SowerWebSeedControllerFindLatest with any type of body
func NewSowerWebSeedControllerFindLatestRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/seeds/latest")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SowerWebSeedControllerListWithResponse request
	SowerWebSeedControllerListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerListResponse, error)

	// SowerWebSeedControllerNewWithBodyWithResponse request with any body
	SowerWebSeedControllerNewWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerNewResponse, error)

	SowerWebSeedControllerNewWithResponse(ctx context.Context, body SowerWebSeedControllerNewJSONRequestBody, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerNewResponse, error)

	// SowerWebSeedControllerFindLatestWithBodyWithResponse request with any body
	SowerWebSeedControllerFindLatestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerFindLatestResponse, error)

	SowerWebSeedControllerFindLatestWithResponse(ctx context.Context, body SowerWebSeedControllerFindLatestJSONRequestBody, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerFindLatestResponse, error)
}

type SowerWebSeedControllerListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Seed
}

// Status returns HTTPResponse.Status
func (r SowerWebSeedControllerListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SowerWebSeedControllerListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SowerWebSeedControllerNewResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Seed
}

// Status returns HTTPResponse.Status
func (r SowerWebSeedControllerNewResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SowerWebSeedControllerNewResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SowerWebSeedControllerFindLatestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Seed
}

// Status returns HTTPResponse.Status
func (r SowerWebSeedControllerFindLatestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SowerWebSeedControllerFindLatestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SowerWebSeedControllerListWithResponse request returning *SowerWebSeedControllerListResponse
func (c *ClientWithResponses) SowerWebSeedControllerListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerListResponse, error) {
	rsp, err := c.SowerWebSeedControllerList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSowerWebSeedControllerListResponse(rsp)
}

// SowerWebSeedControllerNewWithBodyWithResponse request with arbitrary body returning *SowerWebSeedControllerNewResponse
func (c *ClientWithResponses) SowerWebSeedControllerNewWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerNewResponse, error) {
	rsp, err := c.SowerWebSeedControllerNewWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSowerWebSeedControllerNewResponse(rsp)
}

func (c *ClientWithResponses) SowerWebSeedControllerNewWithResponse(ctx context.Context, body SowerWebSeedControllerNewJSONRequestBody, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerNewResponse, error) {
	rsp, err := c.SowerWebSeedControllerNew(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSowerWebSeedControllerNewResponse(rsp)
}

// SowerWebSeedControllerFindLatestWithBodyWithResponse request with arbitrary body returning *SowerWebSeedControllerFindLatestResponse
func (c *ClientWithResponses) SowerWebSeedControllerFindLatestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerFindLatestResponse, error) {
	rsp, err := c.SowerWebSeedControllerFindLatestWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSowerWebSeedControllerFindLatestResponse(rsp)
}

func (c *ClientWithResponses) SowerWebSeedControllerFindLatestWithResponse(ctx context.Context, body SowerWebSeedControllerFindLatestJSONRequestBody, reqEditors ...RequestEditorFn) (*SowerWebSeedControllerFindLatestResponse, error) {
	rsp, err := c.SowerWebSeedControllerFindLatest(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSowerWebSeedControllerFindLatestResponse(rsp)
}

// ParseSowerWebSeedControllerListResponse parses an HTTP response from a SowerWebSeedControllerListWithResponse call
func ParseSowerWebSeedControllerListResponse(rsp *http.Response) (*SowerWebSeedControllerListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SowerWebSeedControllerListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Seed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSowerWebSeedControllerNewResponse parses an HTTP response from a SowerWebSeedControllerNewWithResponse call
func ParseSowerWebSeedControllerNewResponse(rsp *http.Response) (*SowerWebSeedControllerNewResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SowerWebSeedControllerNewResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Seed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSowerWebSeedControllerFindLatestResponse parses an HTTP response from a SowerWebSeedControllerFindLatestWithResponse call
func ParseSowerWebSeedControllerFindLatestResponse(rsp *http.Response) (*SowerWebSeedControllerFindLatestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SowerWebSeedControllerFindLatestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Seed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
