defmodule SowerClient.Orchestration.Deployment do
  use SowerClient.Schema

  OpenApiSpex.schema(%{
    title: "Deployment",
    type: :object,
    properties: %{
      request_id: %Schema{
        type: :string,
        description: "request sid, autogenerated",
        readOnly: true
      },
      sid: %Schema{
        type: :string,
        description: "deployment sid allocated by Sower",
        readOnly: true
      },
      subscription_sids: %Schema{
        type: :array,
        items: %Schema{
          type: :string,
          description: "subscription sids in deployment",
          readOnly: true
        }
      },
      seeds: %Schema{
        type: :array,
        items: SowerClient.Seed.schema()
      },
      deployed_at: %Schema{
        type: :string,
        format: :date_time,
        description: "when the deployment was deployed",
        default: DateTime.from_unix!(0) |> DateTime.to_iso8601()
      }
    },
    required: ~w(subscription_sids)a
  })
end
