defmodule SowerClient.Orchestration.DeploymentRequest do
  use SowerClient.Schema
  use SowerClient.ChannelMessage, event: "deployment:request"

  OpenApiSpex.schema(%{
    title: "DeploymentRequest",
    type: :object,
    properties: %{
      request_id: %Schema{
        type: :string,
        description: "request sid, autogenerated",
        readOnly: true
      },
      subscription_sids: %Schema{
        type: :array,
        items: %Schema{
          type: :string,
          description: "subscription sid allocated by Sower"
        }
      },
      force: %Schema{
        type: :boolean,
        default: false,
        description: "Force deployment even if identical to a previous successful deployment"
      }
    },
    required: [:subscription_sids]
  })

  @doc """
  Wrapper around cast() for generating ids
  """
  def new(map) do
    map
    |> Map.put_new_lazy(:request_id, fn -> SowerClient.Sid.generate("req") end)
    |> cast()
  end
end
