defmodule SowerClient.Orchestration.Deployment do
  use SowerClient.Schema
  use SowerClient.ChannelMessage, event: "deployment"

  OpenApiSpex.schema(%{
    title: "Deployment",
    type: :object,
    properties: %{
      request_id: %Schema{
        type: :string,
        description: "request sid, autogenerated",
        readOnly: true
      },
      sid: %Schema{
        type: :string,
        description: "deployment sid allocated by Sower",
        readOnly: true
      },
      seed_deployments: %Schema{
        type: :array,
        items: SowerClient.Orchestration.SeedDeployment
      },
      deployed_at: %Schema{
        type: :string,
        format: :date_time,
        description: "when the deployment was deployed",
        default: DateTime.from_unix!(0) |> DateTime.to_iso8601()
      },
      skipped: %Schema{
        type: :boolean,
        description:
          "true if deployment was skipped due to matching a previous successful deployment",
        default: false
      }
    },
    required: []
  })
end
