import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sower, SowerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :sentry,
  dsn:
    "https://f106e5c02614e6ad4cc054943811673c@o4507075625287680.ingest.us.sentry.io/4507075627712512",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Sower.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :libcluster,
  topologies: [
    consul: [
      strategy: Cluster.Strategy.Consul,
      config: [
        base_url: "http://localhost:8500",

        # The Consul endpoints used to fetch service nodes.
        list_using: [
          Cluster.Strategy.Consul.Agent,
          {Cluster.Strategy.Consul.Health, [passing: true]}
        ],
        service: [name: "sower"]
      ]
    ]
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
