defmodule Sower.Repo.Migrations.RenameSeedType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:trees), :seed_id, to: :latest_seed_id

    drop constraint(:trees, "trees_seed_id_fkey")

    alter table(:trees) do
      add :booted_seed_id,
          references(:seeds,
            column: :id,
            name: "trees_booted_seed_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :current_seed_id,
          references(:seeds,
            column: :id,
            name: "trees_current_seed_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :profile_seed_id,
          references(:seeds,
            column: :id,
            name: "trees_profile_seed_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      modify :latest_seed_id,
             references(:seeds,
               column: :id,
               name: "trees_latest_seed_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:seeds), :type, to: :seed_type

    alter table(:seeds) do
      modify :seed_type, :text
    end

    drop_if_exists unique_index(:seeds, [:branch, :name, :out_path, :type],
                     name: "seeds_seed_index"
                   )

    create unique_index(:seeds, [:name, :seed_type, :out_path, :branch], name: "seeds_seed_index")

    execute("ALTER TABLE trees alter CONSTRAINT trees_latest_seed_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop_if_exists unique_index(:seeds, [:name, :seed_type, :out_path, :branch],
                     name: "seeds_seed_index"
                   )

    create unique_index(:seeds, [:branch, :name, :out_path, :type], name: "seeds_seed_index")

    alter table(:seeds) do
      modify :type, :text
    end

    rename table(:seeds), :seed_type, to: :type

    drop constraint(:trees, "trees_booted_seed_id_fkey")

    drop constraint(:trees, "trees_current_seed_id_fkey")

    drop constraint(:trees, "trees_profile_seed_id_fkey")

    drop constraint(:trees, "trees_latest_seed_id_fkey")

    alter table(:trees) do
      modify :seed_id,
             references(:seeds,
               column: :id,
               name: "trees_seed_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      remove :profile_seed_id
      remove :current_seed_id
      remove :booted_seed_id
    end

    rename table(:trees), :latest_seed_id, to: :seed_id
  end
end
