defmodule Sower.Repo.Migrations.RenameSeedType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:trees), :type, to: :seed_type

    alter table(:trees) do
      modify :seed_type, :text
    end

    drop_if_exists unique_index(:trees, [:name, :type], name: "trees_tree_index")

    create unique_index(:trees, [:name, :seed_type], name: "trees_tree_index")
  end

  def down do
    drop_if_exists unique_index(:trees, [:name, :seed_type], name: "trees_tree_index")

    create unique_index(:trees, [:name, :type], name: "trees_tree_index")

    alter table(:trees) do
      modify :type, :text
    end

    rename table(:trees), :seed_type, to: :type
  end
end
