defmodule Sower.Repo.Migrations.FixSeedsUniqueIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  import Ecto.Query

  def up do
    drop_if_exists unique_index(:seeds, [:name, :seed_type, :out_path, :branch],
                     name: "seeds_seed_index"
                   )

    delete_duplicate_seeds()

    create unique_index(:seeds, [:name, :seed_type, :out_path], name: "seeds_seed_index")
  end

  def down do
    drop_if_exists unique_index(:seeds, [:name, :seed_type, :out_path], name: "seeds_seed_index")

    create unique_index(:seeds, [:name, :seed_type, :out_path, :branch], name: "seeds_seed_index")
  end

  def delete_duplicate_seeds() do
    query =
      from s in "seeds",
        select: %{id: s.id, rn: over(row_number(), :dup_seeds)},
        windows: [
          dup_seeds: [partition_by: [s.name, s.seed_type, s.out_path], order_by: s.inserted_at]
        ]

    query =
      from s in subquery(query), select: s.id, where: s.rn > 1

    query =
      from s in Sower.Seed, where: s.id in subquery(query)

    query |> Sower.Repo.delete_all()
  end
end
