defmodule Sower.Repo.Migrations.AddSeedUniqueness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:seeds, [:name, :type, :out_path], name: "seeds_seed_index")
  end

  def down do
    drop_if_exists unique_index(:seeds, [:name, :type, :out_path], name: "seeds_seed_index")
  end
end
