defmodule Sower.Repo.Migrations.AddSeedOutPath do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:seeds) do
      add :out_path, :text, null: false
    end
  end

  def down do
    alter table(:seeds) do
      remove :out_path
    end
  end
end
