defmodule Sower.Repo.Migrations.AddTree do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :type, :text, null: false

      add :seed_id,
          references(:seeds,
            column: :id,
            name: "trees_seed_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:trees, [:name, :type], name: "trees_tree_index")
  end

  def down do
    drop_if_exists unique_index(:trees, [:name, :type], name: "trees_tree_index")

    drop constraint(:trees, "trees_seed_id_fkey")

    drop table(:trees)
  end
end
