defmodule Sower.Repo.Migrations.InitInputs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:seeds) do
      add :commit_id, :uuid
    end

    create table(:input_repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :url, :text, null: false
    end

    create unique_index(:input_repositories, [:url], name: "input_repositories_url_index")

    create table(:input_commits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:seeds) do
      modify :commit_id,
             references(:input_commits,
               column: :id,
               name: "seeds_commit_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:input_commits) do
      add :hash, :text, null: false

      add :repository_id,
          references(:input_repositories,
            column: :id,
            name: "input_commits_repository_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:input_commits, [:hash, :repository_id],
             name: "input_commits_repo_hash_index"
           )

    create table(:input_commit_branches, primary_key: false) do
      add :commit_id,
          references(:input_commits,
            column: :id,
            name: "input_commit_branches_commit_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :branch_id, :uuid, null: false, primary_key: true
    end

    create table(:input_branches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:input_commit_branches) do
      modify :branch_id,
             references(:input_branches,
               column: :id,
               name: "input_commit_branches_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:input_branches) do
      add :name, :text, null: false

      add :repository_id,
          references(:input_repositories,
            column: :id,
            name: "input_branches_repository_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:input_branches, [:name, :repository_id],
             name: "input_branches_repo_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:input_branches, [:name, :repository_id],
                     name: "input_branches_repo_name_index"
                   )

    drop constraint(:input_branches, "input_branches_repository_id_fkey")

    alter table(:input_branches) do
      remove :repository_id
      remove :name
    end

    drop constraint(:input_commit_branches, "input_commit_branches_branch_id_fkey")

    alter table(:input_commit_branches) do
      modify :branch_id, :uuid
    end

    drop table(:input_branches)

    drop constraint(:input_commit_branches, "input_commit_branches_commit_id_fkey")

    drop table(:input_commit_branches)

    drop_if_exists unique_index(:input_commits, [:hash, :repository_id],
                     name: "input_commits_repo_hash_index"
                   )

    drop constraint(:input_commits, "input_commits_repository_id_fkey")

    alter table(:input_commits) do
      remove :repository_id
      remove :hash
    end

    drop constraint(:seeds, "seeds_commit_id_fkey")

    alter table(:seeds) do
      modify :commit_id, :uuid
    end

    drop table(:input_commits)

    drop_if_exists unique_index(:input_repositories, [:url], name: "input_repositories_url_index")

    drop table(:input_repositories)

    alter table(:seeds) do
      remove :commit_id
    end
  end
end
