defmodule Sower.Repo.Migrations.AddAccountsUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :oidc_id, :uuid, null: false
      add :username, :citext, null: false
    end

    create unique_index(:users, [:oidc_id], name: "users_unique_oidc_id_index")

    create table(:user_tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:user_tokens)

    drop_if_exists unique_index(:users, [:oidc_id], name: "users_unique_oidc_id_index")

    drop table(:users)
  end
end
