defmodule Sower.Repo.Migrations.AddRepository do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:seeds) do
      add :branch, :text
      add :repository_id, :uuid
    end

    drop_if_exists unique_index(:seeds, [:name, :out_path, :type], name: "seeds_seed_index")

    create table(:input_repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:seeds) do
      modify :repository_id,
             references(:input_repositories,
               column: :id,
               name: "seeds_repository_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:seeds, [:name, :type, :out_path, :branch], name: "seeds_seed_index")

    alter table(:input_repositories) do
      add :url, :text, null: false
    end

    create unique_index(:input_repositories, [:url], name: "input_repositories_url_index")
  end

  def down do
    drop_if_exists unique_index(:input_repositories, [:url], name: "input_repositories_url_index")

    alter table(:input_repositories) do
      remove :url
    end

    drop_if_exists unique_index(:seeds, [:name, :type, :out_path, :branch],
                     name: "seeds_seed_index"
                   )

    drop constraint(:seeds, "seeds_repository_id_fkey")

    alter table(:seeds) do
      modify :repository_id, :uuid
    end

    drop table(:input_repositories)

    create unique_index(:seeds, [:name, :out_path, :type], name: "seeds_seed_index")

    alter table(:seeds) do
      remove :repository_id
      remove :branch
    end
  end
end
