when:
  - event: push

matrix:
  system:
    - x86_64-linux

labels:
  type: local
  system: ${system}

steps:
  - name: check ${system}
    image: bash
    commands:
      - env
      - ls
      - pwd
      - ls $HOME
      - mkdir $HOME
      - nix develop .# --command just check-elixir
