when:
  - event: push

matrix:
  system:
    - x86_64-linux

labels:
  type: local
  system: ${system}

steps:
  - name: build ${system}
    image: bash
    commands:
      - nix develop .# --command seed-ci --attic-upload=true --attic-use=true --cache-build-deps=true --nom=false --sower-seed=true --system ${system}
    environment:
      ATTIC_KEY:
        from_secret: ATTIC_KEY
